# Generated by Django 5.2.1 on 2025-06-13 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soporte',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='devolucion',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='devolucion',
            name='prestamo',
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='padre_fk',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='entregado_por',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='equipos',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='fecha_prestamo',
        ),
        migrations.RemoveField(
            model_name='soporte',
            name='fecha_envio',
        ),
        migrations.RemoveField(
            model_name='soporte',
            name='leida',
        ),
        migrations.RemoveField(
            model_name='soporte',
            name='prestamo',
        ),
        migrations.AddField(
            model_name='categoria',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='prestamos.categoria'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='codigo_interno',
            field=models.CharField(default='CAT001', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'Prestado'), ('mantenimiento', 'En mantenimiento'), ('danado', 'Dañado')], default='disponible', max_length=20),
        ),
        migrations.AddField(
            model_name='categoria',
            name='marca',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='categoria',
            name='modelo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Devolucion',
        ),
    ]
