# Generated by Django 5.2.1 on 2025-05-13 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_cliente_direccion_cliente_identificacion_prestamo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('codigo_interno', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'Prestado'), ('mantenimiento', 'En mantenimiento'), ('dañado', 'Dañado')], default='disponible', max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='fecha_vencimiento',
            new_name='fecha_devolucion',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='interes',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='monto',
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('docente', 'Docente')], default='estudiante', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamo',
            name='entregado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_entregados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('devuelto', 'Devuelto'), ('retrasado', 'Retrasado')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado_final', models.CharField(choices=[('bueno', 'Bueno'), ('dañado', 'Dañado'), ('faltante', 'Faltante')], max_length=20)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='prestamos.prestamo')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.equipo')),
            ],
        ),
        migrations.AddField(
            model_name='prestamo',
            name='equipos',
            field=models.ManyToManyField(related_name='prestamos', to='prestamos.equipo'),
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
