# Generated by Django 5.2.1 on 2025-05-14 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_equipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=256)),
                ('valor', models.IntegerField()),
                ('padre_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.maestra')),
            ],
        ),
    ]
