# Generated by Django 5.2.1 on 2025-05-21 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0004_maestra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestra',
            name='descripcion',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='maestra',
            name='padre_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prestamos.maestra'),
        ),
        migrations.AlterField(
            model_name='maestra',
            name='valor',
            field=models.IntegerField(null=True),
        ),
    ]
