# Generated by Django 5.2.1 on 2025-05-21 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0005_alter_maestra_descripcion_alter_maestra_padre_fk_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='marca',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='estado_final',
            field=models.CharField(choices=[('bueno', 'Bueno'), ('danado', 'Dañado'), ('faltante', 'Faltante')], max_length=20),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.prestamo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'Prestado'), ('mantenimiento', 'En mantenimiento'), ('danado', 'Dañado')], default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.cliente'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='entregado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='equipos',
            field=models.ManyToManyField(to='prestamos.equipo'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('devuelto', 'Devuelto')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='equipo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prestamos.categoria'),
        ),
    ]
